kind: Deployment
apiVersion: apps/v1
metadata:
  name: license-proxyserver-addon-manager
  namespace: open-cluster-management
  labels:
    app: license-proxyserver-addon-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-proxyserver-addon-manager
  template:
    metadata:
      labels:
        app: license-proxyserver-addon-manager
    spec:
      serviceAccountName: license-proxyserver-addon-manager
      containers:
        - name: license-proxyserver-addon-manager
          image: docker.io/rokibulhasan114/license-proxyserver-addon:latest
          imagePullPolicy: Always