apiVersion: licenses.appscode.com.open-cluster-management.io/v1alpha1
kind: LicenseProxyServerConfig
metadata:
  labels:
    app.kubernetes.io/name: licenseproxyserverconfig
    app.kubernetes.io/instance: licenseproxyserverconfig-sample
    app.kubernetes.io/part-of: api
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: api
  name: licenseproxyserverconfig-sample
spec:
  # TODO(user): Add fields here
